version: '3'

services:
  db:
    image: mysql
    volumes:
      - "./sito/db/:/var/lib/mysql"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    
  web:
    image: ubuntu_django:v1
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
